
CREATE OR REPLACE PROCEDURE COMPARE_FACT(
    ID_PACK_OLD NUMBER, 
    ID_PACK_NEW NUMBER, 
    BUILD_DIFF BOOLEAN DEFAULT FALSE
) IS
BEGIN
    
    COMPARE_FACT(ID_PACK_OLD, ID_PACK_NEW);

    
    IF BUILD_DIFF THEN
       
        INSERT INTO TMP_FACT_HISTORY_COMPARE_DIFF (ID_FACT, COL_NAME, COL_OLD_VALUE, COL_NEW_VALUE)
        SELECT f1.ID_FACT, 'VALUE', TO_CHAR(f1.VALUE), TO_CHAR(f2.VALUE)
        FROM FACT_HISTORY f1, FACT_HISTORY f2
        WHERE f1.ID_PACK = ID_PACK_OLD
          AND f2.ID_PACK = ID_PACK_NEW
          AND f1.ID_FACT = f2.ID_FACT
          AND f1.VALUE <> f2.VALUE;
    END IF;
END;
/
