--procedura porównuj¹ca dane
CREATE OR REPLACE PROCEDURE COMPARE_FACT(
    ID_PACK_OLD NUMBER, 
    ID_PACK_NEW NUMBER
) IS
BEGIN
    INSERT INTO TMP_FACT_HISTORY_COMPARE_STATUS (ID_FACT, STATUS)
    SELECT f1.ID_FACT, 1
    FROM FACT_HISTORY f1, FACT_HISTORY f2
    WHERE f1.ID_PACK = ID_PACK_OLD
      AND f2.ID_PACK = ID_PACK_NEW
      AND f1.ID_FACT = f2.ID_FACT
      AND (f1.VALUE <> f2.VALUE); 

    --nowe rekordy
    INSERT INTO TMP_FACT_HISTORY_COMPARE_STATUS (ID_FACT, STATUS)
    SELECT f2.ID_FACT, 2
    FROM FACT_HISTORY f2
    WHERE f2.ID_PACK = ID_PACK_NEW
      AND f2.ID_FACT NOT IN (
        SELECT ID_FACT FROM FACT_HISTORY WHERE ID_PACK = ID_PACK_OLD);

    --usuniête rekordy
    INSERT INTO TMP_FACT_HISTORY_COMPARE_STATUS (ID_FACT, STATUS)
    SELECT f1.ID_FACT, 3
    FROM FACT_HISTORY f1
    WHERE f1.ID_PACK = ID_PACK_OLD
      AND f1.ID_FACT NOT IN (
        SELECT ID_FACT FROM FACT_HISTORY WHERE ID_PACK = ID_PACK_NEW);
END;
/
